[build-system]
requires = ["setuptools", "setuptools-scm", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[project]
dependencies = ["pandas>=3.0.1", "typer>=0.24.1"]
dynamic = ["version"]
name = "tsoppy"
requires-python = ">=3.14"

[project.scripts]
tsoppy = "tsoppy.cli:app"

[project.optional-dependencies]
dev = ["isort==8.0.1", "ruff==0.15.6"]
lint = ["ruff==0.15.6"]
test = ["pytest==9.0.2", "pytest-emoji==0.2.0", "pytest-md==0.2.0"]

[tool.setuptools-git-versioning]
enabled = true
template = "{tag}"
dev_template = "{tag}"
dirty_template = "{tag}"
